/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SetLight, SetLight, AUTO)


PB_BIND(CurrentTime, CurrentTime, AUTO)


PB_BIND(Request, Request, AUTO)


PB_BIND(Log, Log, AUTO)


PB_BIND(Response, Response, AUTO)



